/**
 * Created by xujianwei on 2017/6/26.
 */
callback({
    list:[
        {
            rowId:'0',
            title:'文本框{{value}}',
            //是否必填
            required:true,
            config:{
                type:'text',
                value:'text 1',
                name:'text-name',
                readOnly:true,
                disable:true,
                placeholder:'请输入文本',
            },
            scope:{

            },
            filter:{

            }
        },
        {
            title:'日期组件',
            required:true,
            config:{
                type:'date',
                placeholder:'请选择日期',
                cmd:{
                    $value:'',
                    $model:''
                }
            },
            //hidden:true
        },
        {
            title:'时间选项',
            required:true,
            config:{
                type:'time',
                placeholder:'请选择时间',
                cmd:{
                    "$-value":'',
                    "$-model":''
                }
            }
        },
        {
            title:'自定义内容',
            required:true,
            config:{
                type:'custom',
                template:'<input type="datetime">'
            }
        },
        {
            title:'单选组',
            required:true,
            config:{
                type:'radios',
                $config:{
                    name:'class',
                    dataList:[
                        {
                            content:'数学',
                            value:'1',
                            checked:true
                        },
                        {
                            content:'语文',
                            value:'2'
                        },
                        {
                            content:'化学',
                            value:'3'
                        },
                        {
                            content:'英语',
                            value:'4'
                        },
                        {
                            content:'几何',
                            value:'5'
                        },
                        {
                            content:'生物',
                            value:'6'
                        },
                        {
                            content:'生物1',
                            value:'61'
                        }
                    ]
                }
            }
        },
        {
            title:'图标选择',
            config:{
                type:'icons',
                name:'icon'
            }
        },
        {
            title:'颜色选择',
            config:{
                type:'color',
                name:'icon',
            }
        },
        {
            title:"图标与颜色",
            config:{
                type:'custom',
                template:'<input config="iconConf" value="naozhong" type="icons""><input value="#ff00ff" type="color" $-on:input="iconConf|colorChange" style="margin-left:10px;">',
                scope:{
                    iconConf:{
                        color:'#ff00ff'
                    }
                },
                filter:{
                    colorChange:function(iconConf){
                        return function(){
                            iconConf.color=this.value;
                        }
                    }
                }
            }
        }
    ]
})